services:
  backend:
    build: .
    container_name: calorie_bot
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8010:8000"
    volumes:
      - voice_temp:/shared-voice
    restart: always
    networks:
      - internal
    dns:
      - 8.8.8.8
      - 1.1.1.1

  redis:
    image: redis:7
    container_name: redis
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal

  arqworker_1:
    build: .
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    command: [ "python", "-m", "arq", "app.arq_worker.WorkerSettings" ]
    volumes:
      - voice_temp:/shared-voice
    restart: always
    networks:
      - internal
      - external_net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  arqworker_2:
    build: .
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    command: [ "python", "-m", "arq", "app.arq_worker.WorkerSettings" ]
    volumes:
      - voice_temp:/shared-voice
    restart: always
    networks:
      - internal
      - external_net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  webhook-init:
    build: .
    restart: "no"
    command: [ "python", "app/init_webhook.py" ]
    env_file:
      - .env
    depends_on:
      - backend
    environment:
      - PYTHONPATH=/app
    networks:
      - internal

volumes:
  redis_data:
  voice_temp:


networks:
  internal:
    driver: bridge
  external_net:
    driver: bridge
